esphome:
  name: washer
  platform: ESP8266
  board: nodemcuv2
  includes:
    - VibrationSensor.h
  libraries:
    - "Adafruit LIS3DH"

status_led:
  pin:
    number: D0
    inverted: true
sensor:
  - platform: custom
    lambda: |-
      auto w = new VibrationSensor("washer", 0x18, 0.4);
      App.register_component(w);
      return {w};
    sensors:
      name: "Washer"
  - platform: custom
    lambda: |-
      auto d = new VibrationSensor("dryer", 0x19, 0.4);
      App.register_component(d);
      return {d};
    sensors:
      name: "Dryer"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hotspot_ssid
    password: !secret hotspot_password

captive_portal:

# Enable logging
logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: false

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
